services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vanorika
    ports:
      - "5433:5432"
    volumes:
      - vanorika_pg:/var/lib/postgresql/data
volumes:
  vanorika_pg:
